### ISSUE TITLE
Typos and grammatical errors - add any you find here!

### ISSUE THREAD

**Issue by Telnaior** [KitaenSilva/OSFOP-Project-Repo#21]
Entity in the initial conversation: [I still have a tentative connection to this other me, but with it's system in lockdown, I can't get more information until I deepen the connection somehow]

There shouldn't be an apostrophe in its.

How it should read: [I still have a tentative connection to this other me, but with its system in lockdown, I can't get more information until I deepen the connection somehow]

**Comment by KitaenSilva** [comment]
Not gonna lie, I'm aware of the "it's" vs. "its" issue, and even though I am aware that it is incorrect, I have stubbornly decided that it is instead the English language which is incorrect.

I have no real intent to "correct" the it's vs. its cases because English - despite being my native language and one I am passionate about - is stupid.

[[I say this, but I will probably fix it eventually anyway.]]

**Comment by Telnaior** [comment]
If it helps, my understanding is that its doesn't use an apostrophe for the same reason his and hers don't have apostrophes.

**Comment by KitaenSilva** [comment]
That actually does help a bit - but English is still dumb lol.

I am firmly of the understanding that "it's" would be a possessive "in the possession of it".

I am also aware that this it's vs. its quandary is extremely common - please also keep watch for issues where I mix-up "ie" and "ei" words, such as receipt and ceiling or "weird" vs. "wierd".

o vo_b

**Comment by Pixelguin** [comment]
Also in the intro sequence: "If this software errors..."

Error isn't a verb. "Encounters an error" or "throws an error" would work.
