### ISSUE TITLE
F1, alt-enter and F12 must be disabled

### ISSUE THREAD

**Issue by ShadowJonathan** [KitaenSilva/OSFOP-Project-Repo#49]
Because these keys disrupt gameplay.

A direct fix hasnt been found yet, but we think @vinyldarkscratch's engine can provide a solution to this

**Comment by queengooborg** [comment]
And you're in luck as well!  The SyngleChance engine can remap or entirely disable those keybinds, and in fact already does -- F1 is used for it's keybind configuration, but we can slide that over to another key like F8 or just leave it as-is to disable the default action, and Alt-Enter can be F11 (the standard fullscreen keybind that apparently OneShot didn't listen to XD).  :wink:  Just curious what F12 binds to, by the way, as I've never really tried it out?

**Comment by KitaenSilva** [comment]
We're hoping to outright remove those functions entirely - I don't mind alt+enter being repurposed to F11 tho if that seems like a good idea. Hopefully without stretching the game's aspect ratio, somehow?

As for F12... that resets the game. And would also cause a crash due to lighting system for some reason, but I think that's fixed.

**Comment by queengooborg** [comment]
MKXP already took care of the aspect ratio, glad to say!  MKXP-OneShot also programmed in a nice little variable that can tell the engine to prevent playing in fullscreen for certain scenes (like the camera film puzzle), so that can be used when needed.  ;)  As for F12, I see, in that case let's keep it disabled altogether, 'cause no, having a quick game reset button is not a good idea in public releases.  XD

**Comment by queengooborg** [comment]
Alright, so I made sure that F12 wouldn't reset the game, and bound fullscreen to F11 instead!
